- name: Create unifi group
  become: true
  ansible.builtin.group:
    name: unifi
    state: present

- name: Create unifi user
  become: true
  ansible.builtin.user:
    name: unifi
    shell: /bin/bash
    group: unifi
    state: present

- name: Get user details
  ansible.builtin.getent:
    database: passwd
    key: unifi

- name: Get group details
  getent:
    database: group
    key: unifi

- name: Set user and group id
  set_fact:
    unifi_uid: "{{ ansible_facts.getent_passwd.unifi.1 }}"
    unifi_gid: "{{ ansible_facts.getent_group.unifi.1 }}"

- name: Ensure project directory exists
  become: true
  file:
    path: "{{ docker_projects_directory }}/unifi/"
    owner: unifi
    group: unifi
    mode: "750"
    state: directory


- name: Copy MongoDB init script to project directory
  become: true
  copy:
    src: init-mongo.sh
    dest: "{{ docker_projects_directory }}/unifi/init-mongo.sh"
    owner: unifi
    group: unifi
    mode: "755"

- name: Copy docker compose to project directory
  become: true
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_projects_directory }}/unifi/docker-compose.yml"
    owner: unifi
    group: unifi
    mode: "750"

- name: Run docker compose
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ docker_projects_directory }}/unifi"
    state: present
  register: output
