- name: Ensure /etc/systemd/resolved.conf.d exists
  become: true
  ansible.builtin.file:
    dest: /etc/systemd/resolved.conf.d
    mode: '755'
    owner: root
    group: root
    state: directory

- name: Copy /etc/systemd/resolved.conf.d/00-custom-resolved.conf
  become: true
  ansible.builtin.copy:
    src: 00-custom-resolved.conf
    dest: /etc/systemd/resolved.conf.d/00-custom-resolved.conf
    mode: '644'
    owner: root
    group: root
  notify:  Restart systemd-resolved

- name: Copy /etc/ssh/sshd_config.d
  become: true
  ansible.builtin.copy:
    src: sshd_config.d
    dest: /etc/ssh
    directory_mode: '755'
    mode: '600'
    owner: root
    group: root
  notify:  Restart sshd

- name: Flush handlers
  meta: flush_handlers

- name: Install packages
  become: true
  apt:
    name: 
      - nfs-common
      - cifs-utils
    update_cache: true