- name: Create pihole group
  become: true
  ansible.builtin.group:
    name: pihole
    state: present

- name: Create pihole user
  become: true
  ansible.builtin.user:
    name: pihole
    shell: /bin/bash
    group: pihole
    state: present

- name: Get user details
  ansible.builtin.getent:
    database: passwd
    key: pihole

- name: Get group details
  getent:
    database: group
    key: pihole

- name: Set user and group id
  set_fact:
    pi_hole_uid: "{{ ansible_facts.getent_passwd.pihole.1 }}"
    pi_hole_gid: "{{ ansible_facts.getent_group.pihole.1 }}"

- name: Ensure project directory exists
  become: true
  file:
    path: "{{ docker_projects_directory }}/pi_hole/"
    owner: pihole
    group: pihole
    mode: "750"
    state: directory

- name: Copy docker compose to project directory
  become: true
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_projects_directory }}/pi_hole/docker-compose.yml"
    owner: pihole
    group: pihole
    mode: "750"

- name: Run docker compose
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ docker_projects_directory }}/pi_hole"
    state: present
  register: output
