- name: Create upsnap group
  become: true
  ansible.builtin.group:
    name: upsnap
    state: present

- name: Create upsnap user
  become: true
  ansible.builtin.user:
    name: upsnap
    shell: /bin/bash
    group: upsnap
    state: present

- name: Get user details
  ansible.builtin.getent:
    database: passwd
    key: upsnap

- name: Get group details
  getent:
    database: group
    key: upsnap

- name: Set user and group id
  set_fact:
    upsnap_uid: "{{ ansible_facts.getent_passwd.upsnap.1 }}"
    upsnap_gid: "{{ ansible_facts.getent_group.upsnap.1 }}"

- name: Ensure project directory exists
  become: true
  file:
    path: "{{ docker_projects_directory }}/upsnap/"
    owner: upsnap
    group: upsnap
    mode: "750"
    state: directory

- name: Copy docker compose to project directory
  become: true
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_projects_directory }}/upsnap/docker-compose.yml"
    owner: upsnap
    group: upsnap
    mode: "750"

- name: Run docker compose
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ docker_projects_directory }}/upsnap"
    state: present
  register: output
