- name: Create wireguard group
  become: true
  ansible.builtin.group:
    name: wireguard
    state: present

- name: Create wireguard user
  become: true
  ansible.builtin.user:
    name: wireguard
    shell: /bin/bash
    group: wireguard
    state: present

- name: Get user details
  ansible.builtin.getent:
    database: passwd
    key: wireguard

- name: Get group details
  getent:
    database: group
    key: wireguard

- name: Set user and group id
  set_fact:
    wireguard_uid: "{{ ansible_facts.getent_passwd.wireguard.1 }}"
    wireguard_gid: "{{ ansible_facts.getent_group.wireguard.1 }}"

- name: Ensure project directory exists
  become: true
  file:
    path: "{{ docker_projects_directory }}/wireguard/"
    owner: wireguard
    group: wireguard
    mode: "750"
    state: directory

- name: Copy docker compose to project directory
  become: true
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_projects_directory }}/wireguard/docker-compose.yml"
    owner: wireguard
    group: wireguard
    mode: "750"

- name: Run docker compose
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ docker_projects_directory }}/wireguard"
    state: present
  register: output
