- name: Install packages required to add the Docker repo
  become: true
  ansible.builtin.apt:
    update_cache: true
    package:
      - ca-certificates
      - curl
      - gnupg

- name: Add Docker GPG apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
    state: present

- name: Add Docker Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install docker packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    package:
      - docker-ce={{ docker_version }}~{{ ansible_distribution | lower }}.{{ ansible_distribution_version }}~{{ ansible_distribution_release}}
      - docker-ce-cli={{ docker_version }}~{{ ansible_distribution | lower }}.{{ ansible_distribution_version }}~{{ ansible_distribution_release}}
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Create docker user
  become: true
  ansible.builtin.user:
    name: docker
    shell: /bin/bash
    group: docker
    home: /opt/docker/
    state: present

- name: Ensure docker directory exists
  become: true
  file:
    path: /opt/docker/
    state: directory
    owner: docker
    mode: "755"
    group: docker