- name: Create qbittorrent group
  become: true
  ansible.builtin.group:
    name: qbittorrent
    state: present

- name: Create qbittorrent user
  become: true
  ansible.builtin.user:
    name: qbittorrent
    shell: /bin/bash
    group: qbittorrent
    state: present

- name: Get user details
  ansible.builtin.getent:
    database: passwd
    key: qbittorrent

- name: Get group details
  getent:
    database: group
    key: qbittorrent

- name: Set user and group id
  set_fact:
    qbittorrent_uid: "{{ ansible_facts.getent_passwd.qbittorrent.1 }}"
    qbittorrent_gid: "{{ ansible_facts.getent_group.qbittorrent.1 }}"

- name: Create plex group
  become: true
  ansible.builtin.group:
    name: plex
    state: present

- name: Create plex user
  become: true
  ansible.builtin.user:
    name: plex
    shell: /bin/bash
    group: plex
    state: present

- name: Get user details
  ansible.builtin.getent:
    database: passwd
    key: plex

- name: Get group details
  getent:
    database: group
    key: plex

- name: Set user and group id
  set_fact:
    plex_uid: "{{ ansible_facts.getent_passwd.plex.1 }}"
    plex_gid: "{{ ansible_facts.getent_group.plex.1 }}"

- name: Ensure project directory exists
  file:
    path: ~/docker/servarr/
    state: directory

- name: Copy docker compose to project directory
  template:
    src: docker-compose.yml.j2
    dest: ~/docker/servarr/docker-compose.yml

- name: Run docker compose up
  community.docker.docker_compose_v2:
    project_src: ~/docker/servarr/
    state: present
  register: output
