- name: Create plex group
  become: true
  ansible.builtin.group:
    name: plex
    state: present

- name: Create plex user
  become: true
  ansible.builtin.user:
    name: plex
    shell: /bin/bash
    group: plex
    state: present

- name: Get user details
  ansible.builtin.getent:
    database: passwd
    key: plex

- name: Get group details
  getent:
    database: group
    key: plex

- name: Set user and group id
  set_fact:
    plex_uid: "{{ ansible_facts.getent_passwd.plex.1 }}"
    plex_gid: "{{ ansible_facts.getent_group.plex.1 }}"