- name: Create prowlarr group
  become: true
  ansible.builtin.group:
    name: prowlarr
    state: present

- name: Create prowlarr user
  become: true
  ansible.builtin.user:
    name: prowlarr
    shell: /bin/bash
    group: prowlarr
    state: present

- name: Get user details
  ansible.builtin.getent:
    database: passwd
    key: prowlarr

- name: Get group details
  getent:
    database: group
    key: prowlarr

- name: Set user and group id
  set_fact:
    prowlarr_uid: "{{ ansible_facts.getent_passwd.prowlarr.1 }}"
    prowlarr_gid: "{{ ansible_facts.getent_group.prowlarr.1 }}"
