- name: Create sonarr group
  become: true
  ansible.builtin.group:
    name: sonarr
    state: present

- name: Create sonarr user
  become: true
  ansible.builtin.user:
    name: sonarr
    shell: /bin/bash
    group: sonarr
    state: present

- name: Get user details
  ansible.builtin.getent:
    database: passwd
    key: sonarr

- name: Get group details
  getent:
    database: group
    key: sonarr

- name: Set user and group id
  set_fact:
    sonarr_uid: "{{ ansible_facts.getent_passwd.sonarr.1 }}"
    sonarr_gid: "{{ ansible_facts.getent_group.sonarr.1 }}"