- name: Ensure project directory exists
  become: true
  file:
    path: "{{ docker_projects_directory }}/openvpn/"
    owner: pihole
    group: pihole
    mode: "750"
    state: directory

- name: Copy docker compose to project directory
  become: true
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_projects_directory }}/openvpn/docker-compose.yml"
    owner: pihole
    group: pihole
    mode: "750"

- name: Run docker compose
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ docker_projects_directory }}/openvpn"
    state: present
  register: output
